- uid: aflesch-mt1-ensembles-et-applications-001
  author: aflesch
  discipline: Mathématiques
  title: Appartenance et inclusion
  text: |
    Parmi ces assertions, lesquelles sont vraies ?
  questionType: multiple_choice
  themes:
    - Ensembles et applications
  tags:
    - appartenance
    - inclusion
  timeLimit: 120
  difficulty: 2
  gradeLevel: L1
  explanation: ''
  feedbackWaitTime: 15
  answerOptions:
    - \( \sqrt{2} \in \mathbb{Q} \)
    - \( \sqrt{2} \subset \mathbb{C} \)
    - \( \left\{ \sqrt{2}, \pi \right\} \in \mathbb{R} \)
    - \( \left\{ \sqrt{2}, \pi \right\} \subset \mathbb{C} \)
    - \( \left\{ \varnothing \right\} \in \mathcal{P}(\mathbb{R}) \)
    - \( \left\{ \varnothing \right\} \subset \mathcal{P}(\mathbb{R}) \)
    - >-
      \( \left\{ \varnothing, \left\{ 2 \right\} \right\} \subset
      \mathcal{P}(\mathbb{Q}) \)
    - \( \mathbb{Z} \subset \mathbb{C} \)
    - Aucune des réponses ci-dessus
  correctAnswers:
    - false
    - false
    - false
    - true
    - false
    - true
    - true
    - true
    - false

- uid: aflesch-mt1-ensembles-et-applications-002
  author: aflesch
  discipline: Mathématiques
  title: Injection et surjection
  text: |
    Soit \(f\) l'application définie par:
    \[ \begin{array}{ccccc}
            f & \colon & \mathbb{C} & \rightarrow & \mathbb{R} \\
              &        & z          & \mapsto     & |z|
        \end{array}
    \]
    Que peut-on dire ?
  questionType: single_choice
  themes:
    - Ensembles et applications
  tags:
    - injection
    - surjection
    - bijection
  timeLimit: 60
  difficulty: 2
  gradeLevel: L1
  explanation: ''
  feedbackWaitTime: 15
  answerOptions:
    - \(f\) n'est ni injective ni surjective.
    - \(f\) est injective et non surjective
    - \(f\) est non injective et surjective.
    - \(f\) est injective et surjective.
    - Aucune des réponses ci-dessus.
  correctAnswers:
    - true
    - false
    - false
    - false
    - false

- uid: aflesch-mt1-ensembles-et-applications-003
  author: aflesch
  discipline: Mathématiques
  title: Injection et surjection
  text: |
    Comment choisir les ensembles \(E\) et \(F\) pour que l'application
    \(f\colon E\rightarrow F\) définie par \(f(x)=x^2\) soit bijective?
  questionType: multiple_choice
  themes:
    - Ensembles et applications
  tags:
    - injection
    - surjection
    - bijection
  timeLimit: 120
  difficulty: 2
  gradeLevel: L1
  explanation: ''
  feedbackWaitTime: 15
  answerOptions:
    - \(E=[0,1]\) et \(F=[0,1]\)
    - \(E=[-1,1]\) et \(F=[0,1]\)
    - \(E=\mathbb{R}\) et \(F=\mathbb{R}\)
    - Aucune des propositions ci-dessus
  correctAnswers:
    - true
    - false
    - false
    - false

- uid: aflesch-mt1-ensembles-et-applications-003b
  author: aflesch
  discipline: Mathématiques
  title: Injection et surjection
  text: >
    Soit \(f\) une application de \(E=\left\{ 1;2 \right\}\) vers \(F=\left\{
    3;4;5 \right\}\). Alors:
  questionType: multiple_choice
  themes:
    - Ensembles et applications
  tags:
    - injection
    - surjection
    - bijection
  timeLimit: 120
  difficulty: 2
  gradeLevel: L1
  explanation: ''
  feedbackWaitTime: 15
  answerOptions:
    - \(f\) ne peut pas être injective
    - \(f\) ne peut pas être surjective
    - \(f\) ne peut pas être bijective
    - Aucune des réponses ci-dessus
  correctAnswers:
    - false
    - true
    - true
    - false

- uid: aflesch-mt1-ensembles-et-applications-004
  author: aflesch
  discipline: Mathématiques
  title: Nombre de parties d'un ensemble
  text: |
    Combien y a-t-il d'éléments dans l'ensemble des parties de
    \(\{ \{1;2\};2\}\)?
  questionType: numeric
  themes:
    - Ensembles et applications
  tags:
    - parties
  timeLimit: 120
  difficulty: 2
  gradeLevel: L1
  explanation: ''
  feedbackWaitTime: 15
  correctAnswer: 4

- uid: aflesch-mt1-ensembles-et-applications-005
  author: aflesch
  discipline: Mathématiques
  title: Inclusion d'ensembles
  text: >
    Soit \(E=\{ a;b \}\). Alors, \(\{ \{a\};\{b\} \}\) est inclus dans
    \(\mathcal{P}(E)\).
  questionType: single_choice
  themes:
    - Ensembles et applications
  tags:
    - inclusion
    - parties
  timeLimit: 60
  difficulty: 2
  gradeLevel: L1
  explanation: ''
  feedbackWaitTime: 15
  answerOptions:
    - Vrai
    - Faux
  correctAnswers:
    - true
    - false

- uid: aflesch-mt1-ensembles-et-applications-006
  author: aflesch
  discipline: Mathématiques
  title: Complémentaire d'un ensemble
  text: >
    Soient \(E\) un ensemble et \(A\) et \(B\) deux parties de \(E\). Le
    complémentaire

    de \(A \cup \bar{B}\) est :
  questionType: single_choice
  themes:
    - Ensembles et applications
  tags:
    - complémentaire
    - union
    - intersection
  timeLimit: 30
  difficulty: 1
  gradeLevel: L1
  explanation: ''
  feedbackWaitTime: 15
  answerOptions:
    - \(A \cap \bar{B}\)
    - \(A \cup \bar{B}\)
    - \(\bar{A} \cap B\)
    - \(\bar{A} \cup B\)
    - Aucune des propositions ci-dessus
  correctAnswers:
    - false
    - false
    - true
    - false
    - false

- uid: aflesch-mt1-ensembles-et-applications-007
  author: aflesch
  discipline: Mathématiques
  title: Élément d'un ensemble
  text: |
    Soit \(E\) un ensemble. L'assertion «\(a\) est un élément de \(E\)»
    est synonyme de :
  questionType: multiple_choice
  themes:
    - Ensembles et applications
  tags:
    - appartenance
    - inclusion
  timeLimit: 60
  difficulty: 2
  gradeLevel: L1
  explanation: ''
  feedbackWaitTime: 15
  answerOptions:
    - \( \{a\} \subset E \)
    - \( \{a\} \in E \)
    - \( a \in \mathscr{P}(E) \)
    - \( a \subset E \)
    - Aucune des propositions ci-dessus
  correctAnswers:
    - true
    - false
    - false
    - false
    - false
